version: "3"
services:
  backend:
    build: ./backend/mysbapp
    container_name: springboot
    ports:
      - 8080:8080
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    restart: always
